[2024-05-25T21:13:18.169+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T21:13:18.189+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-25T21:13:18.198+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-25T21:13:18.198+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T21:13:18.211+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 00:15:00+00:00
[2024-05-25T21:13:18.217+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=224) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T21:13:18.218+0000] {standard_task_runner.py:63} INFO - Started process 226 to run task
[2024-05-25T21:13:18.219+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T00:15:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmpkes5edkl']
[2024-05-25T21:13:18.220+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask second-step-el
[2024-05-25T21:13:18.262+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [running]> on host b2cfee8f0b2b
[2024-05-25T21:13:18.347+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:15:00+00:00'
[2024-05-25T21:13:18.349+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T21:13:18.354+0000] {logging_mixin.py:188} INFO - Connection to database was succesful
[2024-05-25T21:13:18.366+0000] {logging_mixin.py:188} INFO - Query completed
[2024-05-25T21:13:18.380+0000] {logging_mixin.py:188} INFO - execute_query_result_set()
[2024-05-25T21:13:18.386+0000] {logging_mixin.py:188} INFO - Connection to database was succesful
[2024-05-25T21:13:18.406+0000] {logging_mixin.py:188} INFO - Inserts performed wihout fail
[2024-05-25T21:13:18.407+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-25T21:13:18.408+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T21:13:18.417+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T00:15:00+00:00, execution_date=20240525T001500, start_date=20240525T211318, end_date=20240525T211318
[2024-05-25T21:13:18.473+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T21:13:18.502+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T21:13:18.510+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-26T00:42:56.350+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T00:42:56.380+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T00:42:56.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T00:42:56.389+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T00:42:56.403+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 00:15:00+00:00
[2024-05-26T00:42:56.413+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T00:15:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmp09kd8wh0']
[2024-05-26T00:42:56.415+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask second-step-el
[2024-05-26T00:42:56.410+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=56) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T00:42:56.424+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2024-05-26T00:42:56.485+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [running]> on host bb8f67d70e6d
[2024-05-26T00:42:56.596+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:15:00+00:00'
[2024-05-26T00:42:56.598+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T00:42:56.603+0000] {logging_mixin.py:188} INFO - Connection to database was succesful
[2024-05-26T00:42:56.610+0000] {logging_mixin.py:188} INFO - query failed, df empty
[2024-05-26T00:42:56.616+0000] {logging_mixin.py:188} INFO - execute_query_result_set()
[2024-05-26T00:42:56.622+0000] {logging_mixin.py:188} INFO - Connection to database was succesful
[2024-05-26T00:42:56.622+0000] {logging_mixin.py:188} INFO - Inserts performed wihout fail
[2024-05-26T00:42:56.623+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-26T00:42:56.623+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T00:42:56.631+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T00:15:00+00:00, execution_date=20240525T001500, start_date=20240526T004256, end_date=20240526T004256
[2024-05-26T00:42:56.681+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-26T00:42:56.698+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T00:42:56.702+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-26T01:06:02.845+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T01:06:02.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:06:02.875+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:06:02.876+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T01:06:02.892+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 00:15:00+00:00
[2024-05-26T01:06:02.898+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=519) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T01:06:02.900+0000] {standard_task_runner.py:63} INFO - Started process 521 to run task
[2024-05-26T01:06:02.900+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T00:15:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmpsd3wjche']
[2024-05-26T01:06:02.901+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask second-step-el
[2024-05-26T01:06:02.951+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [running]> on host bb8f67d70e6d
[2024-05-26T01:06:03.030+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:15:00+00:00'
[2024-05-26T01:06:03.031+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T01:06:03.043+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:06:03.055+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T01:06:03.056+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/Steps.py", line 16, in step_ingesta_transformacion_carga
    df=functions.SQL_query(host,database,user,password,port,extract_query,column_names_e)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/functions.py", line 31, in SQL_query
    df2.columns=column_names
    ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 21 elements, new values have 20 elements
[2024-05-26T01:06:03.068+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T00:15:00+00:00, execution_date=20240525T001500, start_date=20240526T010602, end_date=20240526T010603
[2024-05-26T01:06:03.080+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task second-step-el (Length mismatch: Expected axis has 21 elements, new values have 20 elements; 521)
[2024-05-26T01:06:03.114+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-26T01:06:03.128+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T01:06:03.132+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-26T01:20:03.590+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T01:20:03.609+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:20:03.616+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:20:03.616+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T01:20:03.630+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 00:15:00+00:00
[2024-05-26T01:20:03.636+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=61) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T01:20:03.637+0000] {standard_task_runner.py:63} INFO - Started process 63 to run task
[2024-05-26T01:20:03.638+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T00:15:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmpifgozbhx']
[2024-05-26T01:20:03.639+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask second-step-el
[2024-05-26T01:20:03.681+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [running]> on host 47db2ca9c6bf
[2024-05-26T01:20:03.758+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:15:00+00:00'
[2024-05-26T01:20:03.759+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T01:20:03.765+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:20:03.769+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T01:20:03.770+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/Steps.py", line 16, in step_ingesta_transformacion_carga
    df=functions.SQL_query(host,database,user,password,port,extract_query,column_names_e)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/functions.py", line 31, in SQL_query
    df2.columns=column_names
    ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 21 elements, new values have 20 elements
[2024-05-26T01:20:03.780+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T00:15:00+00:00, execution_date=20240525T001500, start_date=20240526T012003, end_date=20240526T012003
[2024-05-26T01:20:03.793+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task second-step-el (Length mismatch: Expected axis has 21 elements, new values have 20 elements; 63)
[2024-05-26T01:20:03.811+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-26T01:20:03.824+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T01:20:03.830+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-26T01:48:25.978+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T01:48:25.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:48:26.004+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:48:26.004+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T01:48:26.019+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 00:15:00+00:00
[2024-05-26T01:48:26.027+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T01:48:26.028+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2024-05-26T01:48:26.029+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T00:15:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmpxq7_ly_9']
[2024-05-26T01:48:26.030+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask second-step-el
[2024-05-26T01:48:26.068+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [running]> on host 07ce07c9aa35
[2024-05-26T01:48:26.140+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:15:00+00:00'
[2024-05-26T01:48:26.142+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T01:48:26.147+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:48:26.157+0000] {logging_mixin.py:188} INFO - Query completed
[2024-05-26T01:48:26.162+0000] {logging_mixin.py:188} INFO - execute_query_result_set()
[2024-05-26T01:48:26.167+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:48:26.172+0000] {logging_mixin.py:188} INFO - Inserts were comitted
[2024-05-26T01:48:26.172+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-26T01:48:26.172+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T01:48:26.179+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T00:15:00+00:00, execution_date=20240525T001500, start_date=20240526T014825, end_date=20240526T014826
[2024-05-26T01:48:26.202+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-26T01:48:26.215+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T01:48:26.219+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-26T01:49:41.979+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T01:49:42.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:49:42.024+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:49:42.025+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T01:49:42.044+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 00:15:00+00:00
[2024-05-26T01:49:42.058+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T01:49:42.061+0000] {standard_task_runner.py:63} INFO - Started process 110 to run task
[2024-05-26T01:49:42.060+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T00:15:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmp12gu4c9c']
[2024-05-26T01:49:42.062+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask second-step-el
[2024-05-26T01:49:42.139+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [running]> on host 07ce07c9aa35
[2024-05-26T01:49:42.316+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:15:00+00:00'
[2024-05-26T01:49:42.319+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T01:49:42.330+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:49:42.353+0000] {logging_mixin.py:188} INFO - Query completed
[2024-05-26T01:49:42.365+0000] {logging_mixin.py:188} INFO - execute_query_result_set()
[2024-05-26T01:49:42.376+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:49:42.384+0000] {logging_mixin.py:188} INFO - Inserts were comitted
[2024-05-26T01:49:42.385+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-26T01:49:42.386+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T01:49:42.404+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T00:15:00+00:00, execution_date=20240525T001500, start_date=20240526T014942, end_date=20240526T014942
[2024-05-26T01:49:42.437+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-26T01:49:42.464+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T01:49:42.469+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-26T01:59:20.032+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T01:59:20.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:59:20.056+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [queued]>
[2024-05-26T01:59:20.056+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T01:59:20.068+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 00:15:00+00:00
[2024-05-26T01:59:20.074+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T01:59:20.075+0000] {standard_task_runner.py:63} INFO - Started process 66 to run task
[2024-05-26T01:59:20.076+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T00:15:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmp4kvge2d0']
[2024-05-26T01:59:20.077+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask second-step-el
[2024-05-26T01:59:20.118+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T00:15:00+00:00 [running]> on host da1b21f42040
[2024-05-26T01:59:20.190+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:15:00+00:00'
[2024-05-26T01:59:20.192+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T01:59:20.197+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:59:20.209+0000] {logging_mixin.py:188} INFO - Query completed
[2024-05-26T01:59:20.213+0000] {logging_mixin.py:188} INFO - execute_query_result_set()
[2024-05-26T01:59:20.218+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:59:20.223+0000] {logging_mixin.py:188} INFO - Inserts were comitted
[2024-05-26T01:59:20.223+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-26T01:59:20.224+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T01:59:20.230+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T00:15:00+00:00, execution_date=20240525T001500, start_date=20240526T015920, end_date=20240526T015920
[2024-05-26T01:59:20.289+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-26T01:59:20.304+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T01:59:20.308+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
